---
title: "Appointments"
---

<p>Engagement with faculty--both formal and informal--is an important part of the value proposition of graduate school. However, we know that other classes, work schedules, childcare constraints, etc., can make it difficult to hit a set window. You can set up a digital meeting with the instructional team on this booking page. The default appointment is with Zoom, but we am happy to talk by phone, Google Hangouts, or Skype if that is more convenient. The appointment booking page has ~8 hours of time slots throughout the week--and you can always ping us if you need to set up another time. Appointments are optional, but we strongly encourage you to schedule at least 1 or 2. Even if you don't have any questions about class, we value the opportunity to get to know you. Please select a time that you'd like to chat, and message us if you encounter any difficulties.</p>

<iframe src="https://tascott.youcanbook.me/?noframe=true&skipHeaderFooter=true" id="ycbmiframetascott" style="width:100%;height:1000px;border:0px;background-color:transparent;" frameborder="0" allowtransparency="true"></iframe><script>window.addEventListener && window.addEventListener("message", function(event){if (event.origin === "https://tascott.youcanbook.me"){document.getElementById("ycbmiframetascott").style.height = event.data + "px";}}, false);</script>