---
title: "Coding Practice"
output:
  html_document:
    toc: false
---

The following material will be posted on Github via the Discussion board for the class *Team* (2019 is the **Hippogriffs**). Assignments are designed to reinforce the code/lessons covered that week, and provide students a chance to both practice coding and reviewing code. Assignments were completed via private repositories each student set up (via [Github Classrooms](https://classroom.github.com/classrooms)), and each week students will be randomly assigned another student for a code review. Apologies if there are links that don't work, they may be specifically setup for students enrolled in course.

<br>

## Assignments {.tabset .tabset-fade .tabset-pills}

### <small>Week2</small>

### <small>Week3</small>

### <small>Week4</small>

**Week 4 Assignment**

For you assignment this week, we will be practicing subsetting the same data frame we were working with in class, `surveys`. 

The objective of the assignment is for you to write a new, clean script, commit and push it to github, and then someone else will download and run that script on their computer, and file an issue in your repository with some comments about the script.

**Part I: Coding Practice**

1. Create a new script in your `r-davis-in-class-yourname` project named `week_4_assignment_ABC.R` but with your initials in place of ABC. Save it to your `scripts` folder.

2. Read `portal_data_joined.csv` into R using the `read.csv` command and create a dataframe named `surveys` (just like we did in class). 

3. Subset to just the first column and columns five through 8. Include only the first 400 rows. Save this as a dataframe called `surveys_subset`.

4. *CHALLENGE:* Select all rows that have a `hindfoot_length` greater than 32, save these in a new data.frame named `surveys_long_feet`, then plot its `hindfoot_length` values as a histogram using the `hist` function.

5. Change the column `hindfoot_lengths` into a character vector.

6. Plot the `hindfoot_lengths` in a histogram (if this doesn't work, just leave it, and think about it during Part II of the assignment, *wink wink*).

7. Commit & Push the R script to GitHub - check your repository on GitHub and make sure your script is there.

**Part II: Code Review**

Find your code partner’s repository on GitHub, click on the scripts folder, and find the script named `w3_assignment_ABC.R`

Click on the script, then find the RAW button on the right hand side of the screen. Click on RAW.

You should see a plain text version of the script. Right click anywhere on the page, and select “Save As”, save the script to your  scripts folder in your repository. Make sure to change the file extension to `.R` (instead of `.txt`).

Now, if you open up your RProject where you saved the script, you should see it, and better yet, you should have the same path/folder structure that is used in the script (we hope!).

Try to run the script line by line. Where does it break? Can you fix it?
File an Issue in your code partner’s repository. Write up a few sentences describing a few good things about the script (what worked! Was it clearly commented?) and what didn’t (where did it break for you, and why? How might it be fixed?). Remember to be constructive and positive…we’re all learning!

Any questions? comments? Issues? Remember you can always tag us using individual names when you file an issue in the [Discussion repository](https://github.com/gge-ucd/Discussion/issues): @marthawohlfeil, @mcmaurer @ryanpeek, etc.

Thanks!

### <small>Week5</small>

### <small>Week6</small>

### <small>Week7</small>

### <small>Week8</small>

### <small>Week9</small>



