---
title: "Contact"
---

<br>

## Instructors

**Christian John**  
<i class="fa fa-envelope-square" aria-hidden="true"></i> [email](mailto:cjohn@ucdavis.edu) 
[<i class="fa fa-github-square" aria-hidden="true"></i> JepsonNomad](https://github.com/JepsonNomad)  
[<i class="fa fa-twitter-square" aria-hidden="true"></i> \@JepsonNomad](https://twitter.com/JepsonNomad)

I am a 4th year student in the GGE studying bighorn sheep migration in the Sierra Nevada Mountains. I use R for analyzing animal movement and landscape-scale patterns in phenology. My recent R package, `phenomap` is a simple tool for mapping snowmelt and green-up timing over space. If you're interested in movement or MODIS, come talk to me.

**Liza Wood**
<i class="fa fa-envelope-square" aria-hidden="true"></i> [email](mailto:belwood@ucdavis.edu) 

I am a 3rd year student in the GGE studying environmental governance of agricultural systems. I was new to R (and very intimidated) when entering my PhD in 2018, but through a couple courses like R-DAVIS and **a lot** of muddling through self-teaching, I'm now excited about helping promote data literacy. These days, I use R for scraping the web for large amounts of text data (whether it is Tweets scraped from Twitter or thousands of policy documents from government agency websites) using packages like `twitteR` or `rvest`. Generally, I think R can be a bit overwhelming and I look forward to being a part of the de-mystifying process for new coders!

## Teaching Assistants/Classroom Helpers

**Christine Parisek**  
<i class="fa fa-envelope-square" aria-hidden="true"></i> [email](mailto:caparisek@ucdavis.edu) 
[<i class="fa fa-twitter-square" aria-hidden="true"></i> \@caparisek](https://twitter.com/caparisek)
[#sierrafishes](https://twitter.com/search?q=%23sierrafishes&src=typed_query&f=live)

I am a 3rd year PhD student and freshwater ecologist in GGE. I currently study mountain lake fishes and mechanisms that govern their food web's structure and function. My interests range from local scale trophic dynamics in Sierra Nevada lakes, to landscape and global scale patterns in lake distributions. I find working in R to be a bit like a puzzle. It's gratifying to piece together bits of what I know, what I don’t, and ‘solving’ the puzzle to get what I need done. I used to think that people who helped me with my code must just be gifted R wizaRds. Yet an experienced coder once said to me that their knowledge just came from having made that many more coding mistakes over time! I was a novice in R when I was a 1st year, but through the R-Davis course I gained confidence in coding and code problem-solving. Hopefully you enjoy the experience too!

**Conor Higgins**
<i class="fa fa-envelope-square" aria-hidden="true"></i> [email](mailto:rchiggins@ucdavis.edu) 

I’m a 3rd year student in the GGE studying arctic community interactions.  Specifically, I study the relationship between a Greenlandic muskox population and the timing of life history events (phenology) for the plants they consume. I had never used R before grad school, and if I'm honest with myself, I felt so uncomfortable using it at first that my favorite part of R-Davis was closing everything down at the end of each class.  It took a while, but little by little, I've become more comfortable.  I now use R regularly to analyze my data...shout out R-Davis and Google for the help.

**Nick Framsted**
<i class="fa fa-envelope-square" aria-hidden="true"></i> [email](mailto:ntframsted@ucdavis.edu)

I'm a 2nd year student in GGE studying algal responses to climate change in Lake Tahoe. I became familiar with R while doing a minor in statistics and I currently use it to calculate metabolism in aquatic systems. I really enjoy working in R and it's an awesome tool--even if it can be intimidating at first. I look forward to learning with everyone and honing our programming skills this quarter!

<br>

## Course Creators/Former Instructors

**Michael Culshaw-Maurer** 

<i class="fa fa-envelope-square" aria-hidden="true"></i> [email](mailto:mjculshawmaurer@ucdavis.edu)  
[<i class="fa fa-globe" aria-hidden="true"></i> website](https://mcmaurer.github.io/)  
[<i class="fa fa-twitter-square" aria-hidden="true"></i> \@MCulshawMaurer](https://twitter.com/MCulshawMaurer)  
[<i class="fa fa-github-square" aria-hidden="true"></i> MCMaurer](https://github.com/mcmaurer)  

I'm a Ph.D. candidate in the GGE, and I'm co-advised by Jay Rosenheim and Sebastian Schreiber. I study the behavioral responses of insects to natural enemies, ranging from pathogens to predators and parasitoids. I'm working on projects looking at disease-induced cannibalism in *Geocoris pallens* and non-consumptive effects in pea aphids, using a combination of empirical and theoretical approaches.

I came to grad school in 2015 as a complete R novice, but thanks to things like the [Davis R Users Group (D-RUG)](https://d-rug.github.io/), [Data Science Initiative](dsi.ucdavis.edu), and several ECL courses, I've learned a lot in the last few years. In the spring of 2018, I became a certified Software/Data Carpentries instructor and have taught several Carpentries workshops since then. I also help run D-RUG and will be teaching an undergraduate R course this winter.

My favorite part of teaching R is seeing people go from being uncomfortable or intimidated to feeling empowered and capable of expanding their research opportunities and saving time. I remember how daunting R was at first, but now I use it every day and am constantly learning new skills!

<br>

**Martha Zillig** 

<i class="fa fa-envelope-square" aria-hidden="true"></i> [email](mailto:mwohlfeil@ucdavis.edu)  
[<i class="fa fa-globe" aria-hidden="true"></i> website](https://marthawohlfeil.github.io/)  
[<i class="fa fa-github-square" aria-hidden="true"></i> MarthaWohlfeil](https://github.com/MarthaWohlfeil)  
[<i class="fa fa-twitter-square" aria-hidden="true"></i> \@mw_avianecology](https://twitter.com/mw_avianecology)

I am PhD Candidate in Ecology studying avian biogeography in the Great Basin. I am interested in how birds are responding to climate change, and how species distributions are shaped through both biotic and abiotic factors. I get to conduct field work every summer in the Sierra Nevada and in central Nevada where I collected data on bird abundance, insect biomass, microclimate, and vegetation. 

I have been using R since 2016. I was a student in the first ever R-DAVIS course 2016, and have been teaching R in some form since then. I'm very excited to be instructing this course again, and hope to convince students that having a ton of programming experience is NOT necessary to get the most out of R. In addition, I help run [Davis R Users Group (D-RUG)](http://d-rug.github.io/), and co-lead the GGE Statistical Support Group at UC Davis (email me for more details!).

My favorite part about teaching R is when students realize a problem they have struggled with for hours in excel can be solved with a just a few lines of code (see: me early 2016). Teaching R and helping students with data science has been an amazing opportunity, and I am excited to pass on what I have learned to new GGE students. 

<br>

**Ryan Peek** 

<i class="fa fa-envelope-square" aria-hidden="true"></i> [email](mailto:rapeek@ucdavis.edu)  
[<i class="fa fa-globe" aria-hidden="true"></i> website](https://ryanpeek.github.io/)  
[<i class="fa fa-twitter-square" aria-hidden="true"></i> \@riverpeek](https://twitter.com/riverpeek)  
[<i class="fa fa-github-square" aria-hidden="true"></i> ryanpeek](https://github.com/ryanpeek)  
[<i class="ai ai-orcid-square"></i> orcid.org/0000-0002-9577-6885](https://orcid.org/0000-0002-9577-6885)   

I completed my PhD in Ecology (2018) studying ecological responses to freshwater alteration in a sensitive amphibian frog species. I work with many data types, but largely enjoy blending hydrology, genomics, and ecology. I’ve been using R since 2011, and I became a certified Software/Data Carpentry instructor in 2016. I enjoy teaching and helping run Carpentry workshops and R classes to a wide variety of folks including grad students, post docs, professors, industry researchers, and government scientists. I help coordinate the Davis R Users Group (D-RUG), and spearheaded a more organized effort at UC Davis to train fellow grad students/ecologists in data science using the R programming language. My favorite part of teaching programming/coding is seeing folks make their first plot or read in their first dataset, and recognizing that programming can be useful and fun. It is an amazing learning experience to teach, and I hope to continue trying to empower others to become better scientists and data wranglers.

<br>

**Michael Koontz** 

<i class="fa fa-envelope-square" aria-hidden="true"></i> [email](mailto:mikoontz@gmail.com)  
[<i class="fa fa-globe" aria-hidden="true"></i> website](https://michaeljkoontz.weebly.com/)  
[<i class="fa fa-twitter-square" aria-hidden="true"></i> \@_mikoontz](https://twitter.com/_mikoontz)  
[<i class="fa fa-github-square" aria-hidden="true"></i> mikoontz](https://github.com/mikoontz)  
[<i class="ai ai-orcid-square"></i> orcid.org/0000-0002-8276-210X](https://orcid.org/0000-0002-8276-210X)  

I study how complex forest structure affects natural disturbances in the Sierra Nevada mountain range of California. I use satellite imagery, Google Earth Engine, small uncrewed aerial systems (sUAS), and field measurements to map trees and track the spatial patterns of tree mortality as a result of wildfires and bark beetle activity.
I've been using R since 2012, and teaching it since 2014 to a wide variety of folks including grad students, post docs, professors, industry researchers, and government scientists. I became a certified DataCarpentry instructor in 2016.
My favorite part of teaching R is helping people make the leap between novice (no programming experience and not really sure how to start) and beginner (writing their own code and knowledgeable about *how* to learn more). 

<br>


## Data Carpentry  

<i class="fa fa-envelope-square" aria-hidden="true"></i> [info@datacarpentry.org](mailto:info@datacarpentry.org)  
[<i class="fa fa-globe" aria-hidden="true"></i> http://www.datacarpentry.org/](http://www.datacarpentry.org/)  
[<i class="fa fa-twitter-square" aria-hidden="true"></i> \@datacarpentry](https://twitter.com/datacarpentry)  
