Alright folks, it's time for the final assignment of the quarter. The goal here is to generate an scrip that contains several plots and tables. This assignment will put many of your newfound skills to the test, and will ask you to go through data import, cleaning, manipulation, plotting, and communication. 
<br>


#### The Data
For this project you are going to be using some data sets about flights departing New York City in 2013. There are **several** CSV files you will need to use. As with any CSVs you're handed, they might contain some issues...
You should download the [flights](data/nyc_13_flights_small.csv), [planes](data/nyc_13_planes.csv), and [weather](data/nyc_13_weather.csv) CSV files. (Remember to put them into your data folder of your RProject to make reading them in easier!)

Hint! You may have to combine dataframes to answer some questions. Remember our `join` family of functions? You should be able to use the `join` type we covered in class. The `flights` dataset is the biggest one, so you should probably join the other data onto this one, meaning `flights` would be the first (of "left") argument in the left join. You can't join 3 tables together at once, but you can join tables `a` and `b` to make table `ab`, then join `ab` and `c` to get table `abc` which contains the columns from all 3 original tables.


#### Things to Include
1. Plot the departure delay of flights against the precipitation, and include a simple regression line as part of the plot. Hint: there is a `geom_` that will plot a simple `y ~ x` regression line for you, but you might have to use an argument to make sure it's a regular **l**inear **m**odel.
2. Create a figure that has date on the x axis and mean departure delay on the y axis. Plot only months September through December. Somehow distinguish between airline carriers (the method is up to you). 
3. Create a dataframe with these columns: date (year, month and day), mean_temp, where each row represents the airport, based on airport code. Save this is a new csv into you `data` folder called `mean_temp_by_origin.csv`.
4. Make a combination boxplot/scatterplot showing departure delay by manufacturer, and add a facet for whether or not it's raining. Hint: you'll have to make a new column to classify "raining" or "not raining", the exact method is up to you.

For each plot, use `ggsave` to put your ggplot objects into a **new folder** you create called "plots".


```{r}
library(tidyverse)
#flight <- read.csv("data/nyc_13_flights.csv") 
#flight <- flight[sample(1:nrow(flight), size = 50000),]
#write.csv(flight, "data/nyc_13_flights_small.csv", row.names = F)

flight <- read.csv("data/nyc_13_flights_small.csv")
planes <- read.csv("data/nyc_13_planes.csv")
weather <- read.csv("data/nyc_13_weather.csv")

intersect(colnames(flight), colnames(planes))
intersect(colnames(flight), colnames(weather))

df <- flight %>% 
  left_join(planes) %>% 
  left_join(weather)

#Plot the departure delay of flights against the precipitation, and include a simple regression line as part of the plot
colnames(df)
max(df$dep_delay, na.rm = T)
df %>% 
  filter(dep_delay > 0) %>% 
  ggplot(aes(x = precip, y = dep_delay)) +
  geom_point() +
  geom_smooth(method = "lm")

# Create a figure that has date on the x axis and mean departure delay on the y axis. Plot only months September through December. Somehow distinguish between airline carriers (the method is up to you). 
library(lubridate)

df %>% 
  filter(dep_delay > 0) %>% 
  filter(month %in% c(9:12)) %>% 
  mutate(date = ymd(paste(year, month, day, sep = "-"))) %>% 
  ggplot(aes(x = date, y = dep_delay)) + 
  geom_point() +
  facet_wrap(~carrier)
  
# Create a dataframe with the average temperature by month at each origin airport, where the data is wide (i.e. every airport has a column)
df %>% 
  group_by(month, origin) %>% 
  summarize(mean_temp = mean(temp, na.rm = T)) %>% 
  pivot_wider(names_from = origin, values_from = mean_temp)

## Not really convinced we need them to make another plot. Any thoughts on a good function to write?
# Something for each carrier?

unique(df$carrier)
  

```

