---
title: "Lectures"
output:
  html_document:
    toc: false
---

Screencasts of our lectures, livecode, and our class notes^[A `@ucdavis.edu` email/class registration is required to access the google doc] are available below. We are using Google hangouts and screensharing, so bear with us on transitions during lecture and live-coding. In addition, there are a number of great presentations that have been recorded at [Davis R-Users Group](http://d-rug.github.io/) meetings, see the Resources tab.

## Lectures {.tabset .tabset-fade}

### Week 1

* What we covered (<a href="https://dl.dropboxusercontent.com/s/tzri5n40tt4apt2/Week01.R?dl=0" target="_blank">livecode</a>)
* <a href="https://ucdavis.zoom.us/j/99874276705?pwd=VjVvckVpU2NjMUx0YnJaZUQxZ3p0dz09" target="_blank">Live Stream (can be viewed later as well)</a>
* <a href="https://docs.google.com/document/d/1Qn9MHQuCqkMmNFtSi3A3puMEEif3FOUevGnQ7Zb5G8s/edit?usp=sharing" target="_blank">Google Doc Collaborative Notes</a>
* <a href="https://docs.google.com/forms/d/e/1FAIpQLSckEg0FR8czE9vFtG2SCE8MZYkPYu6sgzdqx9FoNOdvFWSD1Q/viewform?usp=sf_link" target="_blank">Post-Class Survey (complete after class)</a>

### Week 2

* What we covered (<a href="https://dl.dropboxusercontent.com/s/1bncm70aaozhx4l/Week02.R?dl=0" target="_blank">livecode</a>)
* <a href="https://ucdavis.zoom.us/j/99874276705?pwd=VjVvckVpU2NjMUx0YnJaZUQxZ3p0dz09" target="_blank">Screencast</a>
* <a href="https://docs.google.com/document/d/18x5hZpA7M0FTNDn0hWA5HV4MyxAC5yZyzVwzXu5oV_0/edit?usp=sharing" target="_blank">Google Doc Collaborative Notes</a>
* <a href="https://docs.google.com/forms/d/e/1FAIpQLSckEg0FR8czE9vFtG2SCE8MZYkPYu6sgzdqx9FoNOdvFWSD1Q/viewform?usp=sf_link" target="_blank">Post-Class Survey (complete after class)</a>

### Week 3

* What we covered (<a href="https://dl.dropboxusercontent.com/s/lndh6xewxgijzn6/Week03.R?dl=0" target="_blank">livecode</a>)
* <a href="https://ucdavis.zoom.us/j/99874276705?pwd=VjVvckVpU2NjMUx0YnJaZUQxZ3p0dz09" target="_blank">Screencast</a>
* <a href="https://docs.google.com/document/d/17cXpETCPatph_tmTXrrCo9o23tFq8fDw7E_2wOcFU6o/edit?usp=sharing" target="_blank">Google Doc Collaborative Notes</a>
* <a href="https://docs.google.com/forms/d/e/1FAIpQLSckEg0FR8czE9vFtG2SCE8MZYkPYu6sgzdqx9FoNOdvFWSD1Q/viewform?usp=sf_link" target="_blank">Post-Class Survey (complete after class)</a>

### Week 4

* What we covered (<a href="https://dl.dropboxusercontent.com/s/4i8o1v7zwgdekiv/Week04.R?dl=0" target="_blank">livecode</a>)
* <a href="https://ucdavis.zoom.us/j/99874276705?pwd=VjVvckVpU2NjMUx0YnJaZUQxZ3p0dz09" target="_blank">Screencast</a>
* <a href="https://docs.google.com/document/d/1S7hjwuNfpsPc-FCRjo3tkI-ycab3H3Dr1WV7N-5ONxA/edit?usp=sharing" target="_blank">Google Doc Collaborative Notes</a>
* <a href="https://docs.google.com/forms/d/e/1FAIpQLSckEg0FR8czE9vFtG2SCE8MZYkPYu6sgzdqx9FoNOdvFWSD1Q/viewform?usp=sf_link" target="_blank">Post-Class Survey (complete after class)</a>

### Week 5

* What we covered (<a href="https://dl.dropboxusercontent.com/s/xnbt9kp2isrdqhr/Week05.R?dl=0" target="_blank">livecode</a>)
* <a href="https://ucdavis.zoom.us/j/99874276705?pwd=VjVvckVpU2NjMUx0YnJaZUQxZ3p0dz09" target="_blank">Screencast</a>
* <a href="https://docs.google.com/document/d/1a32lXEegQtNDpM1WWIAStGjM6i2xQ0KuuPFsMezM5EY/edit?usp=sharing" target="_blank">Google Doc Collaborative Notes</a>
* <a href="https://docs.google.com/forms/d/e/1FAIpQLSckEg0FR8czE9vFtG2SCE8MZYkPYu6sgzdqx9FoNOdvFWSD1Q/viewform?usp=sf_link" target="_blank">Post-Class Survey (complete after class)</a>


### Week 6

* What we covered (<a href="https://dl.dropboxusercontent.com/s/ups7vdhegceehy4/Week06.R?dl=0" target="_blank">livecode</a>)
* <a href="https://ucdavis.zoom.us/j/99874276705?pwd=VjVvckVpU2NjMUx0YnJaZUQxZ3p0dz09" target="_blank">Screencast</a>
* <a href="https://docs.google.com/document/d/1aVk6-88d66ZXOPwCxdRDWwIjztozKMXQqnNIe9vgLRc/edit?usp=sharing" target="_blank">Google Doc Collaborative Notes</a>
* <a href="https://docs.google.com/forms/d/e/1FAIpQLSckEg0FR8czE9vFtG2SCE8MZYkPYu6sgzdqx9FoNOdvFWSD1Q/viewform?usp=sf_link" target="_blank">Post-Class Survey (complete after class)</a>

### Week 7

* What we covered (<a href="https://dl.dropboxusercontent.com/s/hdq4spww650cy2f/Week07.R?dl=0" target="_blank">livecode</a>)
* <a href="https://ucdavis.zoom.us/j/99874276705?pwd=VjVvckVpU2NjMUx0YnJaZUQxZ3p0dz09" target="_blank">Screencast</a>
* <a href="https://docs.google.com/document/d/10twqshouUqOb4kr22AvveSHI1atg_Oh_Zo1f8AqpBeo/edit?usp=sharing" target="_blank">Google Doc Collaborative Notes</a>
* <a href="https://docs.google.com/forms/d/e/1FAIpQLSckEg0FR8czE9vFtG2SCE8MZYkPYu6sgzdqx9FoNOdvFWSD1Q/viewform?usp=sf_link" target="_blank">Post-Class Survey (complete after class)</a>


### Week 8

* What we covered (<a href="https://dl.dropboxusercontent.com/s/vutfx0xrlfofqop/Week08.R?dl=0" target="_blank">livecode</a>)
* <a href="https://ucdavis.zoom.us/j/99874276705?pwd=VjVvckVpU2NjMUx0YnJaZUQxZ3p0dz09" target="_blank">Screencast</a>
* <a href="https://docs.google.com/document/d/1BOYvHmlq0_MrDXYlj_PL-Ibd9kGb1WMhpsqcG7WkLSc/edit?usp=sharing" target="_blank">Google Doc Collaborative Notes</a>
* <a href="https://docs.google.com/forms/d/e/1FAIpQLSckEg0FR8czE9vFtG2SCE8MZYkPYu6sgzdqx9FoNOdvFWSD1Q/viewform?usp=sf_link" target="_blank">Post-Class Survey (complete after class)</a>


### Week 9

* What we covered (<a href="https://dl.dropboxusercontent.com/s/43xyeq2xbpgfzed/Week09.R?dl=0" target="_blank">livecode</a>)
* <a href="https://ucdavis.zoom.us/j/99874276705?pwd=VjVvckVpU2NjMUx0YnJaZUQxZ3p0dz09" target="_blank">Screencast</a>
* <a href="https://docs.google.com/document/d/1BsPJDXYmWwJLt4DrNiQo7QE6Lz_wUUgngYjUw8AThYg/edit?usp=sharing" target="_blank">Google Doc Collaborative Notes</a>
* <a href="https://docs.google.com/forms/d/e/1FAIpQLSckEg0FR8czE9vFtG2SCE8MZYkPYu6sgzdqx9FoNOdvFWSD1Q/viewform?usp=sf_link" target="_blank">Post-Class Survey (complete after class)</a>


### Week 10

* What we covered (<a href="https://dl.dropboxusercontent.com/s/cjp0m9cwatrqjl5/Week10.R?dl=0" target="_blank">livecode</a>)
* <a href="https://ucdavis.zoom.us/j/99874276705?pwd=VjVvckVpU2NjMUx0YnJaZUQxZ3p0dz09" target="_blank">Screencast</a>
* <a href="https://docs.google.com/document/d/13a1x5WedlcVja-TSnC8n3uUoIBrSQ4AfoLMg5uyR2DI/edit?usp=sharing" target="_blank">Google Doc Collaborative Notes</a>
* <a href="https://docs.google.com/forms/d/e/1FAIpQLSckEg0FR8czE9vFtG2SCE8MZYkPYu6sgzdqx9FoNOdvFWSD1Q/viewform?usp=sf_link" target="_blank">Post-Class Survey (complete after class)</a>
* <a href="https://forms.gle/PAbLdiaGwT4ejtAU6" target="_blank">POST-COURSE SURVEY: PLEASE TAKE YOUR TIME</a>
