---
title: "Syllabus"
date: '*Updated:* `r format(Sys.time(), "%Y-%b-%d")`'
---

# 

<br>

## Course Description

Computer literacy is now essential in all aspects of science. Data management skills are needed for entering data without errors, storing it in a usable way, and extracting key aspects of the data for analysis. Basic programming is required for everything from accessing and managing data, data visualization, to statistical analysis, and modeling. This course will provide an introduction to data/project management, manipulation, visualization and analysis, across a broad set of ecological data (spatial, genomic, field, etc). Class will typically consist of short introductions or question & answer sessions, followed by hands on computing exercises. The course will be taught using git/Github, R/RStudio, RMarkdown, and SQLite, but the concepts learned will easily apply to all programming languages and database management systems. **No background in databases or R/computational experience is required.**

## Prerequisite Knowledge and Skills

A willingess to practice coding and embrace the R language.

## Purpose of Course

In this course you will learn fundamental aspects of computer programming that are necessary for conducting ecological research. By the end of the course you will be able to use these tools to import data into R, wrangle various types of data, summarize and analyze data, create visualizations and maps, write reports/manuscripts/CV’s in RMarkdown, save and export data/figures, as well as collaborate on Github with version-controlled projects.

The focus of this course is to provide graduate students with training that develops and teaches the tools applicable to the entire process of **reproducible data-driven research** and encourage the use of open-source tools. By learning how to get the computer to do your work for you, you will be able to do more science faster, and your future-self will thank you.

## Course Objectives

Students completing this course should be able to:

 - Read, Import/Export data
 - Tidy/summarize and analyze data
 - Write simple functions/programs in R
 - Automate data analysis
 - Scrape websites for data
 - Map/manipulate spatial (raster/vector) data
 - Learn how to apply these tools to address scientific research questions

## Schedule

<!-- devtools::install_github("hadley/emo") 
http://emoji.muan.co/ to look up emoji

/-->

```{r echo=F, eval=T}
#devtools::install_github("hadley/emo")
library(emo, quietly = T)

# green check emoji are things we've completed or already are in/updated, 
# gray check boxes are content we have but haven't added to website yet
```

#### Week 1

 - `r emo::ji("white_check_mark")` Course Intro
 - `r emo::ji("ballot_box_with_check")` Intro to Git and RStudio
 - `r emo::ji("white_check_mark")` Intro to R

#### Week 2

 - `r emo::ji("white_check_mark")` Project management
 - spreadsheets with demo
 - `r emo::ji("white_check_mark")` Data frames & subsetting
 - super basic plotting (both in base R and ggplot2)

#### Week 3

 - `r emo::ji("white_check_mark")` `dplyr` (includes a pipeline of import, manipulation, visualization)
 - `r emo::ji("white_check_mark")` `tidyr`: with many datasets

#### Week 4

 - `r emo::ji("ballot_box_with_check")` visualization do's and don'ts

#### Week 5

 - `r emo::ji("white_check_mark")` Data import; include a list-- how many different kinds of file extensions-- crowd-sourced list, R can do all of it)
 - `r emo::ji("white_check_mark")` `purrr` package

#### Week 6

 - `r emo::ji("ballot_box_with_check")` `lubridate` (import, manipulate, visualize pipeline time; time series example, CO2 web data, Maelle Salmon's tweet mining)

#### Week 7

 - `r emo::ji("white_check_mark")` joins (lots of practice! Use Hadley's examples, use ModernDiveR examples)

#### Week 8

 - `r emo::ji("ballot_box_with_check")` spatial (see [Mapping In R](https://ryanpeek.github.io/mapping_in_R/index.html)) 

#### Week 9

 - `r emo::ji("ballot_box_with_check")` custom functions
 - `r emo::ji("ballot_box_with_check")` for loops

#### Week 10

 - broom package, stats (R)
 - random sampling (refer to ModernDiveR with nycflights13 data)
